config/routes.rb
RedmineApp::Application.routes.draw do
  get 'issues/graphs/old', :to => 'graphs#old_issues'
  get 'issues/graphs/issue_age_graph', :to => 'graphs#issue_age_graph'
  get 'projects/:project_id/issues/graphs/old', :to => 'graphs#old_issues'
  get ':project_id/issue_age_graph', :to => 'graphs#issue_age_graph'
  get 'issues/graphs/growth', :to => 'graphs#issue_growth'
  get 'issues/graphs/issue_growth_graph', :to => 'graphs#issue_growth_graph'
  get 'projects/:project_id/issues/graphs/growth', :to => 'graphs#issue_growth'
  get ':project_id/issue_growth_graph', :to => 'graphs#issue_growth_graph'
  get 'issues/graphs/bug_growth', :to => 'graphs#bug_growth'
  get 'issues/graphs/bug_growth_graph', :to => 'graphs#bug_growth_graph'
  get 'projects/:project_id/issues/graphs/bug_growth', :to => 'graphs#bug_growth'
  get ':project_id/bug_growth_graph', :to => 'graphs#bug_growth_graph'
  get 'graphs/recent-status-changes', :to => 'graphs#recent_status_changes_graph'
  get 'graphs/recent-assigned-to-changes', :to => 'graphs#recent_assigned_to_changes_graph'
  get 'graphs/target-version/:id', :to => 'graphs#target_version_graph'
  get 'graphs/old_issues', :to => 'graphs#issue_age_graph'
  get 'graphs/issue_growth', :to => 'graphs#issue_growth_graph'
end

app/views/issues/_list_simple.html.erb
<% if issues && issues.any? %>
<%= form_tag({}, :data => {:cm_url => issues_context_menu_path}) do %>
  <table class="list list-simple issues">
    <thead><tr>
    <th class="id">#</th>
    <th class="project"><%=l(:field_project)%></th>
    <th class="status"><%=l(:field_status)%></th>
    <th class="subject"><%=l(:field_subject)%></th>
    </tr></thead>
    <tbody>
    <% for issue in issues %>
    <tr id="issue-<%= h(issue.id) %>" class="hascontextmenu <%= issue.css_classes %>">
      <td class="id">
        <%= check_box_tag("ids[]", issue.id, false, :style => 'display:none;', :id => nil) %>
        <%= link_to("#{issue.tracker} ##{issue.id}", issue_path(issue)) %>
      </td>
      <td class="project"><%= link_to_project(issue.project) %></td>
      <td class="status"><%= issue.status %></td>
      <td class="subject">
        <span><%= link_to(issue.subject, issue_path(issue)) %></span>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>